// Generated by cc_code_gen
#include <iostream>
#include <cstdint>
#include <vector>
#include <string>

using CellType = wchar_t;

const size_t kMemorySize = 65535;

auto Compute(std::vector<CellType>& memory) -> void ;

auto Init(std::vector<CellType>& memory) -> void;

auto main() -> int{
	auto memory=std::vector<CellType>();
	memory.resize(kMemorySize);
	Init(memory);
	Compute(memory);
	return EXIT_SUCCESS;
}


auto Compute(std::vector<CellType>& memory) -> void {
	size_t ptr_pos = 0;
	while(memory[ptr_pos]) { 
		std::wcout << memory[ptr_pos]; 
		ptr_pos += (1); 
	} 
}
auto Init(std::vector<CellType>& memory) -> void{
	std::string remain = "Hello World";
	for(size_t i = 0;i < remain.size();i++)
		memory[i] = remain[i];
}